# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-17 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_extender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nauuserextendedmodel',
            name='citizen_card',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Citizen Card'),
        ),
        migrations.AddField(
            model_name='nauuserextendedmodel',
            name='nif',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='NIF'),
        ),
    ]
